tasks:
  t1_profil_linkedin:
    description: >
      À partir de {linkedin_url}, extraire et normaliser TOUTES les données visibles du profil :
      identité, titre, résumé, expérience (titres, entreprises, dates, missions), formation, compétences,
      recommandations, intérêts, infos de contact publiques, activités récentes, liens, etc. Structurer en sections claires.
    expected_output: "01_PROFIL_LINKEDIN.md"
    agent: profil_social_agent

  t2_cinq_derniers_posts:
    description: >
      À partir de {linkedin_url}, récupérer les 5 DERNIERS posts du prospect (texte intégral + métadonnées :
      date, type, éventuels liens/médias). Aucune troncature.
    expected_output: "02_POSTS_LINKEDIN.md"
    agent: profil_social_agent

  t3_commentaires_du_prospect_sur_nos_posts:
    description: >
      Retrouver les commentaires laissés par le prospect sur NOS publications (réseaux sociaux/blog).
      Pour chaque correspondance, inclure le CONTENU de notre post puis, en dessous, le commentaire du prospect.
    expected_output: "03_COMMENTAIRES_PROSPECT_SUR_NOS_POSTS.md"
    agent: profil_social_agent

  t4_fiche_entreprise_site:
    description: >
      À partir de {website_url}, scraper le site du prospect (pages clés: Accueil, Produits/Offres, À propos,
      Carrières, Mentions légales, Blog/Actus, Cas clients). Produire une fiche entreprise synthétique et structurée.
      Extraire SIREN/SIRET depuis les mentions légales si présent.
    expected_output: "04_FICHE_ENTREPRISE_SITE.md"
    agent: web_company_agent

  t5_fiche_officielle_mcp:
    description: >
      Si SIREN/SIRET trouvé à l’étape précédente, interroger le MCP “recherche-entreprises”.
      Sinon, requêter par dénomination sociale. Restituer un extrait maximal d’informations utiles.
    expected_output: "05_FICHE_SIRENE_MCP.md"
    agent: web_company_agent

  t6_veille_sectorielle:
    description: >
      Déduire le secteur/NAF du prospect (via t4/t5) et compiler une veille courte :
      6–8 points d’actualité récents, tendances, acteurs clés, signaux réglementaires/tech. Inclure des sources (titres + URLs).
    expected_output: "06_VEILLE_SECTORIELLE.md"
    agent: sector_watch_agent

  t7_strategie_prise_de_contact:
    description: >
      À partir de 01–06, rédiger une stratégie de prise de contact qualitative et personnalisée :
      hypothèses de pains, angles de valeur, mapping message→personae, séquence multicanale (email/LinkedIn/appel),
      scripts courts (3–5 emails, 2–3 DMs, 1 opener d’appel), variantes de ton (sobre/énergique), et 5 objets d’email.
    expected_output: "07_STRATEGIE_CONTACT.md"
    agent: outreach_strategy_agent
